set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

if(NOT TINYCV_TOOLCHAIN_DIR)
    set(TINYCV_TOOLCHAIN_DIR "/usr")
    if(NOT EXISTS ${TINYCV_TOOLCHAIN_DIR})
        message(FATAL_ERROR "`TINYCV_TOOLCHAIN_DIR` not set.")
    endif()
elseif(NOT EXISTS ${TINYCV_TOOLCHAIN_DIR})
    message(FATAL_ERROR "`TINYCV_TOOLCHAIN_DIR`(${TINYCV_TOOLCHAIN_DIR}) not found.")
endif()

set(CMAKE_C_COMPILER ${TINYCV_TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${TINYCV_TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
